
automation:
  - alias: Pool - publish zenith yaml
    description: ''
    trigger:
      - platform: state
        entity_id:
          - sun.sun
        attribute: next_noon
      - platform: state
        entity_id:
          - sensor.piscine_eclairage_temperature
          - sensor.piscine_eclairage_temperature_2
    condition: []
    action:
      - if:
        - condition: not
          conditions:
            - condition: or
              conditions:
                - condition: state
                  entity_id: sensor.piscine_eclairage_temperature
                  state: unavailable
                - condition: state
                  entity_id: sensor.piscine_eclairage_temperature
                  state: unknown
                - condition: state
                  entity_id: sensor.piscine_eclairage_temperature_2
                  state: unavailable
                - condition: state
                  entity_id: sensor.piscine_eclairage_temperature_2
                  state: unknown
        then:
          - service: mqtt.publish
            data:
              topic: ha/pool
              payload_template: >-
                {"next_noon": "{{ as_timestamp(state_attr('sun.sun', 'next_noon')) |
                timestamp_custom('%H:%M') }}",
                "temperature": {{ states('sensor.piscine_eclairage_temperature') }},
                "temperature_ext": {{ states('sensor.piscine_eclairage_temperature_2') }}
                }
              retain: true
    mode: single
    
    