
automation:
  - alias: Pool - publish zenith yaml
    description: ''
    trigger:
      - platform: state
        entity_id:
          - sun.sun
        attribute: next_noon
      - platform: state
        entity_id:
          - sensor.piscine_eclairage_temperature
          - input_number.coeff_filtration
    condition: []
    action:
      - service: mqtt.publish
        data:
          topic: ha/pool
          payload_template: >-
            {"next_noon": "{{ as_timestamp(state_attr('sun.sun', 'next_noon')) |
            timestamp_custom('%H:%M') }}",
            "temperature": {{ states('sensor.piscine_eclairage_temperature') }},
            "temperature_ext": {{ states('sensor.piscine_eclairage_temperature_2') }},
            "coeff_filt": {{ states('input_number.coeff_filtration') }}
            }
          retain: true
    mode: single
    